baseURL = "https://maaaathieu4a.github.io/"
publishDir = "./"
languageCode = "fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "hugo-theme-tokiwa"
title = "Mathieu blog perso"
author = "Mathieu"
hasCJKLanguage=true

[markup.goldmark.renderer]
unsafe= true

[params]
description = """
Bienvenue
"""
favicon = "static/img/favicon-32.png"
math = true # for introducing $KaTEX$
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = true # for font Noto Serif etc.
bannerFont = "fonts/exampleFont" # custom your own font for the title.

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[social]
    instagram = "https://www.instagram.com/maaaathieu4a"
    youtube = "https://www.youtube.com/channel/UCOKCAUjcTEgdy910X3uQyhQ"
    github="http://github.com/maaaathieu4a"

[outputs]
  home = ["HTML", "JSON"]

